### ISSUE TITLE
can i use yolo v3 with your modification?

### ISSUE THREAD

**Issue by yojun0611** [rafaelpadilla/darknet#1]
hello, rafaelpadilla
first of all, thank you for your work because it's exactly what I want.
I am very new in this field. so I have little knowledge about computer science.

I want to get objected bounding box and re-label to re-train model.
As my first step, I need objected bounding box for re-labeling to re-train model.
(which exactly your work provides. thx again)

so I did 'git clone' your repo. and I modified Makefile from GPU=0 to 1 for using GPU.
and I did 'make'. then I did do your example.

It did look like working properly. However, it couldn't detect any objects like below.
![default](https://user-images.githubusercontent.com/37891962/38077453-f9e71bfe-3373-11e8-96d9-b2f1eea60245.JPG)
can u tell me what did I wrong? 

and next question is the same as the title.
I tried to do your example with yolov3.cfg & weight.
then I got an error like below.
![image](https://user-images.githubusercontent.com/37891962/38077593-70539c4a-3374-11e8-9ab6-83bdf5e84a78.png)
is there any way to use yolo v3 with your modification?

I hope that you could help me. Thank you a lot again anyway.

**Comment by rafaelpadilla** [comment]
Dear @yojun0611,

First of all, sorry for the delay on answering your message. Somehow I am not being alerted when an  issues is opened.

Answering your questions:

1) As the weight file distributed in this repository was about 268MB, I had to commit this file with git-lfs (Large File Storage). It will not work if you just download the project.
Please, **try cloning the project instead of downloading it**. Make sure the yolo-voc_final.weights is about 268MB. If not, download it manually from the repo.
Please, let me know if you got it working.

2) No, this repository is for YOLO V2. Soon I will apply these same features (testing multiple images, testing with different threshold values, etc) with YOLO V3. I believe that if you click on the "start" button, you will be notified with the new changes.

Thanks a lot for your feedback!
